name: 'Demo approvals'

on:
  push:
    branches:
      - "main"

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    environment: 'DEV'
    steps:
      - name: dev plan
        run: echo "DEV PLAN"
      - name: dev apply
        run: echo "DEV APPLY"

  int-deploy:
    runs-on: ubuntu-latest
    environment: 'INT'
    steps:
      - name: int plan
        run: echo "INT PLAN"
      - name: int apply
        run: echo "INT APPLY"
        
  prod-plan:
    runs-on: 'ubuntu-latest'
    environment: 'PROD'
    needs: [dev-deploy, int-deploy]
    steps:
      - name: prod plan
        run: echo "PROD PLAN"
        
  prod-apply:
    runs-on: 'ubuntu-latest'
    environment: 'PROD'
    needs: [prod-plan]
    steps:
      - name: prod apply
        run: echo "PROD APPLY"
